name: Service Example
on:
  push:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest
    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  node:10.16-jessie

    services:
      postgres:
        image: chatterbugapp/print-env

    steps:
    - uses: actions/checkout@v1
    - run: ls
